version: 0.2

phases:
#  install:
#    runtime-versions:
#      nodejs: 20
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./dist s3://mimesweeper.variable.team
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./dist/index.html s3://mimesweeper.variable.team/
      - aws cloudfront create-invalidation --distribution-id E18SWP6XMGAWB0 --paths /index.html
#  artifacts:
#    files:
#      - "dist/*"
#      - "dist/**/*"
    #name: $(date +%Y-%m-%d)
    #discard-paths: yes
    #base-directory: location
    #cache:
    #paths:
    # - paths
